// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/logs/v1/logs.proto

package io.opentelemetry.proto.logs.v1;

public final class LogsProto {
  private LogsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&opentelemetry/proto/logs/v1/logs.proto" +
      "\022\033opentelemetry.proto.logs.v1\032*opentelem" +
      "etry/proto/common/v1/common.proto\032.opent" +
      "elemetry/proto/resource/v1/resource.prot" +
      "o\"L\n\010LogsData\022@\n\rresource_logs\030\001 \003(\0132).o" +
      "pentelemetry.proto.logs.v1.ResourceLogs\"" +
      "\276\001\n\014ResourceLogs\022;\n\010resource\030\001 \001(\0132).ope" +
      "ntelemetry.proto.resource.v1.Resource\022]\n" +
      "\034instrumentation_library_logs\030\002 \003(\01327.op" +
      "entelemetry.proto.logs.v1.Instrumentatio" +
      "nLibraryLogs\022\022\n\nschema_url\030\003 \001(\t\"\276\001\n\032Ins" +
      "trumentationLibraryLogs\022V\n\027instrumentati" +
      "on_library\030\001 \001(\01325.opentelemetry.proto.c" +
      "ommon.v1.InstrumentationLibrary\0224\n\004logs\030" +
      "\002 \003(\0132&.opentelemetry.proto.logs.v1.LogR" +
      "ecord\022\022\n\nschema_url\030\003 \001(\t\"\326\002\n\tLogRecord\022" +
      "\026\n\016time_unix_nano\030\001 \001(\006\022D\n\017severity_numb" +
      "er\030\002 \001(\0162+.opentelemetry.proto.logs.v1.S" +
      "everityNumber\022\025\n\rseverity_text\030\003 \001(\t\022\014\n\004" +
      "name\030\004 \001(\t\0225\n\004body\030\005 \001(\0132\'.opentelemetry" +
      ".proto.common.v1.AnyValue\022;\n\nattributes\030" +
      "\006 \003(\0132\'.opentelemetry.proto.common.v1.Ke" +
      "yValue\022 \n\030dropped_attributes_count\030\007 \001(\r" +
      "\022\r\n\005flags\030\010 \001(\007\022\020\n\010trace_id\030\t \001(\014\022\017\n\007spa" +
      "n_id\030\n \001(\014*\303\005\n\016SeverityNumber\022\037\n\033SEVERIT" +
      "Y_NUMBER_UNSPECIFIED\020\000\022\031\n\025SEVERITY_NUMBE" +
      "R_TRACE\020\001\022\032\n\026SEVERITY_NUMBER_TRACE2\020\002\022\032\n" +
      "\026SEVERITY_NUMBER_TRACE3\020\003\022\032\n\026SEVERITY_NU" +
      "MBER_TRACE4\020\004\022\031\n\025SEVERITY_NUMBER_DEBUG\020\005" +
      "\022\032\n\026SEVERITY_NUMBER_DEBUG2\020\006\022\032\n\026SEVERITY" +
      "_NUMBER_DEBUG3\020\007\022\032\n\026SEVERITY_NUMBER_DEBU" +
      "G4\020\010\022\030\n\024SEVERITY_NUMBER_INFO\020\t\022\031\n\025SEVERI" +
      "TY_NUMBER_INFO2\020\n\022\031\n\025SEVERITY_NUMBER_INF" +
      "O3\020\013\022\031\n\025SEVERITY_NUMBER_INFO4\020\014\022\030\n\024SEVER" +
      "ITY_NUMBER_WARN\020\r\022\031\n\025SEVERITY_NUMBER_WAR" +
      "N2\020\016\022\031\n\025SEVERITY_NUMBER_WARN3\020\017\022\031\n\025SEVER" +
      "ITY_NUMBER_WARN4\020\020\022\031\n\025SEVERITY_NUMBER_ER" +
      "ROR\020\021\022\032\n\026SEVERITY_NUMBER_ERROR2\020\022\022\032\n\026SEV" +
      "ERITY_NUMBER_ERROR3\020\023\022\032\n\026SEVERITY_NUMBER" +
      "_ERROR4\020\024\022\031\n\025SEVERITY_NUMBER_FATAL\020\025\022\032\n\026" +
      "SEVERITY_NUMBER_FATAL2\020\026\022\032\n\026SEVERITY_NUM" +
      "BER_FATAL3\020\027\022\032\n\026SEVERITY_NUMBER_FATAL4\020\030" +
      "*X\n\016LogRecordFlags\022\037\n\033LOG_RECORD_FLAG_UN" +
      "SPECIFIED\020\000\022%\n LOG_RECORD_FLAG_TRACE_FLA" +
      "GS_MASK\020\377\001Bk\n\036io.opentelemetry.proto.log" +
      "s.v1B\tLogsProtoP\001Z<github.com/open-telem" +
      "etry/opentelemetry-proto/gen/go/logs/v1b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor,
        new java.lang.String[] { "ResourceLogs", });
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor,
        new java.lang.String[] { "Resource", "InstrumentationLibraryLogs", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "Logs", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor,
        new java.lang.String[] { "TimeUnixNano", "SeverityNumber", "SeverityText", "Name", "Body", "Attributes", "DroppedAttributesCount", "Flags", "TraceId", "SpanId", });
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
