// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/metrics/v1/metrics.proto

package io.opentelemetry.proto.metrics.v1;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntGauge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntGauge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntSum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntSum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntHistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntHistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntHistogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntHistogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_IntExemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_IntExemplar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,opentelemetry/proto/metrics/v1/metrics" +
      ".proto\022\036opentelemetry.proto.metrics.v1\032*" +
      "opentelemetry/proto/common/v1/common.pro" +
      "to\032.opentelemetry/proto/resource/v1/reso" +
      "urce.proto\"X\n\013MetricsData\022I\n\020resource_me" +
      "trics\030\001 \003(\0132/.opentelemetry.proto.metric" +
      "s.v1.ResourceMetrics\"\312\001\n\017ResourceMetrics" +
      "\022;\n\010resource\030\001 \001(\0132).opentelemetry.proto" +
      ".resource.v1.Resource\022f\n\037instrumentation" +
      "_library_metrics\030\002 \003(\0132=.opentelemetry.p" +
      "roto.metrics.v1.InstrumentationLibraryMe" +
      "trics\022\022\n\nschema_url\030\003 \001(\t\"\304\001\n\035Instrument" +
      "ationLibraryMetrics\022V\n\027instrumentation_l" +
      "ibrary\030\001 \001(\01325.opentelemetry.proto.commo" +
      "n.v1.InstrumentationLibrary\0227\n\007metrics\030\002" +
      " \003(\0132&.opentelemetry.proto.metrics.v1.Me" +
      "tric\022\022\n\nschema_url\030\003 \001(\t\"\315\004\n\006Metric\022\014\n\004n" +
      "ame\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\014\n\004unit\030\003" +
      " \001(\t\022A\n\tint_gauge\030\004 \001(\0132(.opentelemetry." +
      "proto.metrics.v1.IntGaugeB\002\030\001H\000\0226\n\005gauge" +
      "\030\005 \001(\0132%.opentelemetry.proto.metrics.v1." +
      "GaugeH\000\022=\n\007int_sum\030\006 \001(\0132&.opentelemetry" +
      ".proto.metrics.v1.IntSumB\002\030\001H\000\0222\n\003sum\030\007 " +
      "\001(\0132#.opentelemetry.proto.metrics.v1.Sum" +
      "H\000\022I\n\rint_histogram\030\010 \001(\0132,.opentelemetr" +
      "y.proto.metrics.v1.IntHistogramB\002\030\001H\000\022>\n" +
      "\thistogram\030\t \001(\0132).opentelemetry.proto.m" +
      "etrics.v1.HistogramH\000\022U\n\025exponential_his" +
      "togram\030\n \001(\01324.opentelemetry.proto.metri" +
      "cs.v1.ExponentialHistogramH\000\022:\n\007summary\030" +
      "\013 \001(\0132\'.opentelemetry.proto.metrics.v1.S" +
      "ummaryH\000B\006\n\004data\"M\n\005Gauge\022D\n\013data_points" +
      "\030\001 \003(\0132/.opentelemetry.proto.metrics.v1." +
      "NumberDataPoint\"\272\001\n\003Sum\022D\n\013data_points\030\001" +
      " \003(\0132/.opentelemetry.proto.metrics.v1.Nu" +
      "mberDataPoint\022W\n\027aggregation_temporality" +
      "\030\002 \001(\01626.opentelemetry.proto.metrics.v1." +
      "AggregationTemporality\022\024\n\014is_monotonic\030\003" +
      " \001(\010\"\255\001\n\tHistogram\022G\n\013data_points\030\001 \003(\0132" +
      "2.opentelemetry.proto.metrics.v1.Histogr" +
      "amDataPoint\022W\n\027aggregation_temporality\030\002" +
      " \001(\01626.opentelemetry.proto.metrics.v1.Ag" +
      "gregationTemporality\"\303\001\n\024ExponentialHist" +
      "ogram\022R\n\013data_points\030\001 \003(\0132=.opentelemet" +
      "ry.proto.metrics.v1.ExponentialHistogram" +
      "DataPoint\022W\n\027aggregation_temporality\030\002 \001" +
      "(\01626.opentelemetry.proto.metrics.v1.Aggr" +
      "egationTemporality\"P\n\007Summary\022E\n\013data_po" +
      "ints\030\001 \003(\01320.opentelemetry.proto.metrics" +
      ".v1.SummaryDataPoint\"\303\002\n\017NumberDataPoint" +
      "\022;\n\nattributes\030\007 \003(\0132\'.opentelemetry.pro" +
      "to.common.v1.KeyValue\022A\n\006labels\030\001 \003(\0132-." +
      "opentelemetry.proto.common.v1.StringKeyV" +
      "alueB\002\030\001\022\034\n\024start_time_unix_nano\030\002 \001(\006\022\026" +
      "\n\016time_unix_nano\030\003 \001(\006\022\023\n\tas_double\030\004 \001(" +
      "\001H\000\022\020\n\006as_int\030\006 \001(\020H\000\022;\n\texemplars\030\005 \003(\013" +
      "2(.opentelemetry.proto.metrics.v1.Exempl" +
      "ar\022\r\n\005flags\030\010 \001(\rB\007\n\005value\"\342\002\n\022Histogram" +
      "DataPoint\022;\n\nattributes\030\t \003(\0132\'.opentele" +
      "metry.proto.common.v1.KeyValue\022A\n\006labels" +
      "\030\001 \003(\0132-.opentelemetry.proto.common.v1.S" +
      "tringKeyValueB\002\030\001\022\034\n\024start_time_unix_nan" +
      "o\030\002 \001(\006\022\026\n\016time_unix_nano\030\003 \001(\006\022\r\n\005count" +
      "\030\004 \001(\006\022\013\n\003sum\030\005 \001(\001\022\025\n\rbucket_counts\030\006 \003" +
      "(\006\022\027\n\017explicit_bounds\030\007 \003(\001\022;\n\texemplars" +
      "\030\010 \003(\0132(.opentelemetry.proto.metrics.v1." +
      "Exemplar\022\r\n\005flags\030\n \001(\r\"\201\004\n\035ExponentialH" +
      "istogramDataPoint\022;\n\nattributes\030\001 \003(\0132\'." +
      "opentelemetry.proto.common.v1.KeyValue\022\034" +
      "\n\024start_time_unix_nano\030\002 \001(\006\022\026\n\016time_uni" +
      "x_nano\030\003 \001(\006\022\r\n\005count\030\004 \001(\006\022\013\n\003sum\030\005 \001(\001" +
      "\022\r\n\005scale\030\006 \001(\021\022\022\n\nzero_count\030\007 \001(\006\022W\n\010p" +
      "ositive\030\010 \001(\0132E.opentelemetry.proto.metr" +
      "ics.v1.ExponentialHistogramDataPoint.Buc" +
      "kets\022W\n\010negative\030\t \001(\0132E.opentelemetry.p" +
      "roto.metrics.v1.ExponentialHistogramData" +
      "Point.Buckets\022\r\n\005flags\030\n \001(\r\022;\n\texemplar" +
      "s\030\013 \003(\0132(.opentelemetry.proto.metrics.v1" +
      ".Exemplar\0320\n\007Buckets\022\016\n\006offset\030\001 \001(\021\022\025\n\r" +
      "bucket_counts\030\002 \003(\004\"\202\003\n\020SummaryDataPoint" +
      "\022;\n\nattributes\030\007 \003(\0132\'.opentelemetry.pro" +
      "to.common.v1.KeyValue\022A\n\006labels\030\001 \003(\0132-." +
      "opentelemetry.proto.common.v1.StringKeyV" +
      "alueB\002\030\001\022\034\n\024start_time_unix_nano\030\002 \001(\006\022\026" +
      "\n\016time_unix_nano\030\003 \001(\006\022\r\n\005count\030\004 \001(\006\022\013\n" +
      "\003sum\030\005 \001(\001\022Y\n\017quantile_values\030\006 \003(\0132@.op" +
      "entelemetry.proto.metrics.v1.SummaryData" +
      "Point.ValueAtQuantile\022\r\n\005flags\030\010 \001(\r\0322\n\017" +
      "ValueAtQuantile\022\020\n\010quantile\030\001 \001(\001\022\r\n\005val" +
      "ue\030\002 \001(\001\"\207\002\n\010Exemplar\022D\n\023filtered_attrib" +
      "utes\030\007 \003(\0132\'.opentelemetry.proto.common." +
      "v1.KeyValue\022J\n\017filtered_labels\030\001 \003(\0132-.o" +
      "pentelemetry.proto.common.v1.StringKeyVa" +
      "lueB\002\030\001\022\026\n\016time_unix_nano\030\002 \001(\006\022\023\n\tas_do" +
      "uble\030\003 \001(\001H\000\022\020\n\006as_int\030\006 \001(\020H\000\022\017\n\007span_i" +
      "d\030\004 \001(\014\022\020\n\010trace_id\030\005 \001(\014B\007\n\005value\"\326\001\n\014I" +
      "ntDataPoint\022=\n\006labels\030\001 \003(\0132-.openteleme" +
      "try.proto.common.v1.StringKeyValue\022\034\n\024st" +
      "art_time_unix_nano\030\002 \001(\006\022\026\n\016time_unix_na" +
      "no\030\003 \001(\006\022\r\n\005value\030\004 \001(\020\022>\n\texemplars\030\005 \003" +
      "(\0132+.opentelemetry.proto.metrics.v1.IntE" +
      "xemplar:\002\030\001\"Q\n\010IntGauge\022A\n\013data_points\030\001" +
      " \003(\0132,.opentelemetry.proto.metrics.v1.In" +
      "tDataPoint:\002\030\001\"\276\001\n\006IntSum\022A\n\013data_points" +
      "\030\001 \003(\0132,.opentelemetry.proto.metrics.v1." +
      "IntDataPoint\022W\n\027aggregation_temporality\030" +
      "\002 \001(\01626.opentelemetry.proto.metrics.v1.A" +
      "ggregationTemporality\022\024\n\014is_monotonic\030\003 " +
      "\001(\010:\002\030\001\"\234\002\n\025IntHistogramDataPoint\022=\n\006lab" +
      "els\030\001 \003(\0132-.opentelemetry.proto.common.v" +
      "1.StringKeyValue\022\034\n\024start_time_unix_nano" +
      "\030\002 \001(\006\022\026\n\016time_unix_nano\030\003 \001(\006\022\r\n\005count\030" +
      "\004 \001(\006\022\013\n\003sum\030\005 \001(\020\022\025\n\rbucket_counts\030\006 \003(" +
      "\006\022\027\n\017explicit_bounds\030\007 \003(\001\022>\n\texemplars\030" +
      "\010 \003(\0132+.opentelemetry.proto.metrics.v1.I" +
      "ntExemplar:\002\030\001\"\267\001\n\014IntHistogram\022J\n\013data_" +
      "points\030\001 \003(\01325.opentelemetry.proto.metri" +
      "cs.v1.IntHistogramDataPoint\022W\n\027aggregati" +
      "on_temporality\030\002 \001(\01626.opentelemetry.pro" +
      "to.metrics.v1.AggregationTemporality:\002\030\001" +
      "\"\243\001\n\013IntExemplar\022F\n\017filtered_labels\030\001 \003(" +
      "\0132-.opentelemetry.proto.common.v1.String" +
      "KeyValue\022\026\n\016time_unix_nano\030\002 \001(\006\022\r\n\005valu" +
      "e\030\003 \001(\020\022\017\n\007span_id\030\004 \001(\014\022\020\n\010trace_id\030\005 \001" +
      "(\014:\002\030\001*\214\001\n\026AggregationTemporality\022\'\n#AGG" +
      "REGATION_TEMPORALITY_UNSPECIFIED\020\000\022!\n\035AG" +
      "GREGATION_TEMPORALITY_DELTA\020\001\022&\n\"AGGREGA" +
      "TION_TEMPORALITY_CUMULATIVE\020\002*;\n\016DataPoi" +
      "ntFlags\022\r\n\tFLAG_NONE\020\000\022\032\n\026FLAG_NO_RECORD" +
      "ED_VALUE\020\001Bt\n!io.opentelemetry.proto.met" +
      "rics.v1B\014MetricsProtoP\001Z?github.com/open" +
      "-telemetry/opentelemetry-proto/gen/go/me" +
      "trics/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor,
        new java.lang.String[] { "ResourceMetrics", });
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor,
        new java.lang.String[] { "Resource", "InstrumentationLibraryMetrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "Metrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor,
        new java.lang.String[] { "Name", "Description", "Unit", "IntGauge", "Gauge", "IntSum", "Sum", "IntHistogram", "Histogram", "ExponentialHistogram", "Summary", "Data", });
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", "IsMonotonic", });
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "Labels", "StartTimeUnixNano", "TimeUnixNano", "AsDouble", "AsInt", "Exemplars", "Flags", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "Labels", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "BucketCounts", "ExplicitBounds", "Exemplars", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "Scale", "ZeroCount", "Positive", "Negative", "Flags", "Exemplars", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor,
        new java.lang.String[] { "Offset", "BucketCounts", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "Labels", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "QuantileValues", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor,
        new java.lang.String[] { "Quantile", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor,
        new java.lang.String[] { "FilteredAttributes", "FilteredLabels", "TimeUnixNano", "AsDouble", "AsInt", "SpanId", "TraceId", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_IntDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_opentelemetry_proto_metrics_v1_IntDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntDataPoint_descriptor,
        new java.lang.String[] { "Labels", "StartTimeUnixNano", "TimeUnixNano", "Value", "Exemplars", });
    internal_static_opentelemetry_proto_metrics_v1_IntGauge_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_opentelemetry_proto_metrics_v1_IntGauge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntGauge_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_IntSum_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_opentelemetry_proto_metrics_v1_IntSum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntSum_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", "IsMonotonic", });
    internal_static_opentelemetry_proto_metrics_v1_IntHistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_opentelemetry_proto_metrics_v1_IntHistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntHistogramDataPoint_descriptor,
        new java.lang.String[] { "Labels", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "BucketCounts", "ExplicitBounds", "Exemplars", });
    internal_static_opentelemetry_proto_metrics_v1_IntHistogram_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_opentelemetry_proto_metrics_v1_IntHistogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntHistogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_IntExemplar_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_opentelemetry_proto_metrics_v1_IntExemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_IntExemplar_descriptor,
        new java.lang.String[] { "FilteredLabels", "TimeUnixNano", "Value", "SpanId", "TraceId", });
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
